name: flutter_hive_tdo
description: Flutter Hive Todo app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.2
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  # flutter_beautiful_popup: ^1.7.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_native_splash: ^2.4.3
  flutter_slider_drawer: ^2.1.1
  ftoast: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  lottie: ^3.1.3
  panara_dialogs: ^0.1.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter_native_splash:
  color: "#D1D9E6" # Color of the background of the splash screen
  image: assets/img/icon.jpg # image path
  android_12:
    image: assets/img/icon.jpg # image path
    color: "#D1D9E6" # Color of the background of the splash screen
flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
